src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, success_view


urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("", include("recipes.urls")),
    path("", include("users.urls")),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('success/', success_view, name='success'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home, RecipesListView, RecipesDetailView

app_name = "recipes"

urlpatterns = [
    path("", home, name="home"),
    path("recipes/", RecipesListView.as_view(), name="recipes"),
    path("recipes/<pk>", RecipesDetailView.as_view(), name="detail"),
]

src/users/urls.py
from django.urls import path
from .views import profile, signup_view
from django.urls import re_path
from django.conf import settings
from django.views.static import serve


app_name = "users"

urlpatterns = [
    path("profile/", profile.as_view(), name="profile"),
    path('signup/', signup_view, name='signup'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
] 

src/recipes/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
difficulty_choices = (
    ("Easy", "easy"),
    ("Medium", "medium"),
    ("Intermediate", "intermediate"),
    ("Hard", "hard"),
)

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    cooking_time = models.IntegerField(
        help_text="Enter the cooking time in minutes", default=0
    )
    ingredients = models.CharField(
        max_length=250, help_text="Enter each ingredient separated by a comma"
    )
    difficulty = models.CharField(
        max_length=120, choices=difficulty_choices, default="Easy"
    )
    pic = models.ImageField(
        upload_to="recipes",
        help_text="Upload Image (Min.250px)",
        default="no_picture.jpg",
    )
    author = models.CharField(max_length=120, default="anonymous")
    instructions = models.TextField(default="No instructions ...")
    date_created = models.DateField(default=timezone.now)

    def __str__(self):
        return f"{self.name} - {self.difficulty} - {self.cooking_time}"

    def save(self, *args, **kwargs):
        self.calc_difficulty()
        super().save(*args, **kwargs)

    def calc_difficulty(self):
        ingredients_len = len(self.ingredients.split(", "))
        if self.cooking_time < 10 and ingredients_len < 4:
            self.difficulty = "Easy"
        elif self.cooking_time < 10 and ingredients_len >= 4:
            self.difficulty = "Medium"
        elif self.cooking_time >= 10 and ingredients_len < 4:
            self.difficulty = "Intermediate"
        elif self.cooking_time >= 10 and ingredients_len >= 4:
            self.difficulty = "Hard"

src/recipes/forms.py
from django import forms

CHART__CHOICES = (
   ('#1', 'Bar chart'),
   ('#2', 'Pie chart'),
   ('#3', 'Line Chart'),
)

class RecipesSearchForm(forms.Form):
    recipe_name = forms.CharField(max_length=100)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

src/recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
import pandas as pd
from .forms import RecipesSearchForm
from .utils import get_recipename_from_id, get_chart
from django.db.models import Q


# Create your views here.
def home(request):
    return render(request, "recipes/recipes_home.html")


class RecipesListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipe_list.html'
    login_url = '/login/'  # Redirect to login page if not authenticated

    def get(self,request):
        form = RecipesSearchForm()
        recipes = Recipe.objects.all()
        return render(request, 'recipes/recipes_list.html', {'form': form, 'recipes': recipes})
    
    def post(self, request):
        form = RecipesSearchForm(request.POST)
        recipes = Recipe.objects.all()
        chart = None

        if form.is_valid():
            recipe_name = form.cleaned_data.get('recipe_name')
            chart_type = form.cleaned_data.get('chart_type')

            qs = Recipe.objects.filter(Q(name__icontains=recipe_name) | Q(ingredients__icontains=recipe_name))
            if qs.exists():
                recipes = pd.DataFrame(qs.values())
                recipes['difficulty'] = recipes.apply(lambda row: get_recipename_from_id(row['id']).difficulty, axis=1)
                chart = get_chart(chart_type, recipes, labels=recipes['id'].values)
            else:
                recipes = pd.DataFrame()
        
        context = {
            'form': form,
            'recipes': recipes,
            'chart': chart,
        }
        return render(request, 'recipes/recipes_list.html', context)

class RecipesDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/recipes_details.html"

src/recipes/templates/recipes/recipes_details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <title>Recipes Details</title>
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #f8eff6;
        }
        
        header {
            display: flex;
            justify-content: space-between;
            text-align: center;
        }

        nav {
            display: flex;
            align-items: center;
            background: #eff8f1;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            overflow: hidden;
            display: flex;
            align-items: center;
            flex: 1;
        }

        .navitem {
            display: block;
            text-align: center;
            text-decoration: none;
            flex: 1;
        }

        .navitem a {
            text-decoration: none;
            color: #000;
            font-size: 20px;
        }

        .navitem h1 {
            font-size: 35px;
            color: #87723b;
        }

        main {
            padding: 15px 150px;
            display: flex;
            flex-direction: row;
            justify-content: center;
        }

        .left {
            padding:25px;
        }

        .left img {
            min-width: 500px;
            max-width: 100%;
            height: auto;
        }

        .details {
            padding: 25px;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
    </style>
</head>
<body>
    <nav>
        <ul>
            <li class="navitem"><a href="{% url 'recipes:recipes' %}">Recipes</a></li>
            <li class="navitem"><a href="{% url 'users:profile' %}">Profile</a></li>
            <li class="navitem"><h1>Recipe App</h1></li>
            <li class="navitem"><a href ="https://vanuck.github.io/Website-Portfolio/" target="_blank">About Me</a></li>
            <li class="navitem"><a href ="{%url 'logout' %}"> Logout </a></li>
        </ul>
    </nav>
    <main>
        <div class="left">
            <h2>{{object.name}}</h2>
            <img src="{{object.pic.url}}" width="200" height="300" />
        </div>
        <div class="details">
            <p><b>Author: </b>{{object.author}}</p>
            <p><b>Cooking time: </b>{{object.cooking_time}}</p>
            <p><b>Difficulty: </b>{{object.difficulty}}</p>
            <p><b>Ingredients: </b>{{object.ingredients}}</p>
            <p><b>Instructions: </b>{{object.instructions}}</p>
        </div>
    </main>
</body>
</html>

src/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Link to Google Fonts for Roboto font family -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    
    <!-- Link to external CSS stylesheet for additional styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

    <!-- Favicon for the website -->
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/icon">

    <title>The Recipe App</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            height: 100%;
            font-family: 'Roboto', Arial, sans-serif;
        }

        /* Background image styling with a smooth transition */
        .background {
            position: absolute;
            width: 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
            animation: changeBackground 25s infinite;
            z-index: -1; /* Ensure background is behind other content */
        }

        /* Keyframe animation for cycling through background images */
        @keyframes changeBackground {
            10% { background-image: url('../../static/recipes/images/donair.jpg'); }
            25% { background-image: url('../../static/recipes/images/chicken.jpg'); }
            35% { background-image: url('../../static/recipes/images/grilledcheese.jpg'); }
            50% { background-image: url('../../static/recipes/images/fajitas.jpg'); }
            66% { background-image: url('../../static/recipes/images/pizza.jpg'); }
            80% { background-image: url('../../static/recipes/images/spaghetti.jpg'); }
            100% { background-image: url('../../static/recipes/images/foodbackground.jpg'); }
        }

        nav {
            display: flex;
            align-items: center;
            background: #ddec0c;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            overflow: hidden;
            display: flex;
            align-items: center;
            flex: 1;
        }

        .navitem {
            display: block;
            text-align: center;
            text-decoration: none;
            flex: 1;
        }

        .navitem a {
            text-decoration: none;
            color: #000;
            font-size: 30px;
        }

        .navitem h1 {
            font-size: 45px;
            color: #0c1ae9;
        }


        /* Search bar styling */
        .search-bar {
            display: flex;
            align-items: center;
        }

        .search-bar input {
            padding: 10px;
            font-size: 16px;
            border-radius: 15px;
            border: 1px solid #ddd;
            margin-right: 10px;
        }

        .search-bar button {
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 15px;
            background-color: rgb(80, 4, 4);
            color: white;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .search-bar button:hover {
            background-color: rgb(120, 0, 0);
        }

        main {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 80vh;
        }

        .main-box {
            padding: 40px 60px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background: rgba(255, 255, 255, 0.8);
            border-radius: 15px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(5px);
        }

        .main-box h1 {
            font-size: 30px;
            color: rgb(80, 4, 4);
        }

        .button {
            padding: 10px 20px;
            background-color: #426552;
            color: white;
            border: none;
            border-radius: 15px;
            font-size: 18px;
            cursor: pointer;
            transition: transform 0.3s ease-in-out;
        }

        .button:hover {
            transform: scale(1.05);
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            font-size: 18px;
            text-align: center;
            padding: 15px;
            background: rgba(62, 61, 61, 0.5);
            color: rgb(14, 7, 83);
        }
    </style>
</head>
<body>
    <div class="background"></div>

    <nav>
        <ul>
            <li class="navitem"><a href="{% url 'recipes:recipes' %}">Recipes</a></li>
            <li class="navitem"><a href="{% url 'users:profile' %}">Your Profile</a></li>
            <li class="navitem"><h1>The Recipe App</h1></li>
            <li class="navitem"><a href="https://vanuck.github.io/Website-Portfolio/" target="_blank">About Me</a></li>
            <li class="navitem"><a href="{% url 'users:signup' %}">Sign Up</a></li>
        </ul>

</nav>
<main>
    <div class="main-box">
        <h1>Are you a <b>Chefosaurus Rex!</b></h1>
        <a class="button" href="{% url 'login' %}">Login</a>
    </div>
</main>

    <div class="footer">
        <p>Follow us on social media!</p>
        <!-- Will add social media icons and links here -->
    </div>
</body>
</html>

src/recipes/templates/recipes/recipes_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <title>Recipe List</title>
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <style>
        .uniform-image {
            width: 500px;      
            height: 500px;     
            object-fit: cover; 
            display: block;    
        }
        
        body {
            margin: 0;
            padding: 0;
            background-color: #f0efcb;
        }
        
         /* Background image styling with a smooth transition */
         .background {
            position: absolute;
            width: 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
            animation: changeBackground 25s infinite;
            z-index: -1; /* Ensure background is behind other content */
        }

        /* Keyframe animation for cycling through background images */
        @keyframes changeBackground {
            10% { background-image: url('../../static/recipes/images/donair.jpg'); }
            25% { background-image: url('../../static/recipes/images/chicken.jpg'); }
            35% { background-image: url('../../static/recipes/images/grilledcheese.jpg'); }
            50% { background-image: url('../../static/recipes/images/fajitas.jpg'); }
            66% { background-image: url('../../static/recipes/images/pizza.jpg'); }
            80% { background-image: url('../../static/recipes/images/spaghetti.jpg'); }
            100% { background-image: url('../../static/recipes/images/foodbackground.jpg'); }
        }
        
        header {
            display: flex;
            justify-content: space-between;
            text-align: center;
        }

        nav {
            display: flex;
            align-items: center;
            background: #ddec0c;
        }

        nav ul {
            list-style-type: none;
            padding: 0;
            overflow: hidden;
            display: flex;
            align-items: center;
            flex: 1;
        }

        .navitem {
            display: block;
            text-align: center;
            text-decoration: none;
            flex: 1;
        }

        .navitem a {
            text-decoration: none;
            color: #000;
            font-size: 30px;
        }

        .navitem h1 {
            font-size: 45px;
            color: #0c1ae9;
        }

          
        main {
            margin-top: 50px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .main-box {
            padding: 30px;
            width: 80%;
            display: flex;
            align-items: center;
            justify-content: center;
            background: rgba(255, 255, 255, 0.562);
            border-radius: 15px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(7px);
            flex-direction: column;
        }

        .main-box form {
            margin-bottom: 15px;
        }

        .main-box form input {
            font-size: 18px;
            background-color: #2d5753;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 3px;
            margin: 5px;
        }

        .main-box form input::placeholder {
            color: #000;
            font-size: 18px;
        }

        .main-box select {
            font-size: 18px;
            background-color: #2d5753;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 3px;
            margin: 5px;
        }

        .main-box button {
            padding: 3px 10px;
            margin: 5px;
            background-color: #0e3b22;
            color: white;
            border: none;
            border-radius: 5px;
            font-size: 18px;
            cursor: pointer;
            transition: 0.3s ease-in-out;
        }

        .main-box button:hover {
            transform: scale(1.25);
        }

        .main-box ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-wrap: wrap; 
}

.main-box ul li {
    margin: 15px;
    width: 300px; 
    height: 300px; 
    box-sizing: border-box; 
    display: flex;
    flex-direction: column; 
    align-items: center; 
}

.main-box ul li img {
    width: 100%; 
    height: 80%; 
    object-fit: cover; 
}

.main-box ul li h2 {
    margin: 10px 0; 
    text-align: center; 
}
    </style>
</head>
<body>
    
    <div class="background"></div>
    
    <nav>
        <ul>
            <li class="navitem"><a href="{% url 'recipes:recipes' %}">Recipes</a></li>
            <li class="navitem"><a href="{% url 'users:profile' %}">Profile</a></li>
            <li class="navitem"><h1>Recipe App</h1></li>
            <li class="navitem"><a href ="https://vanuck.github.io/Website-Portfolio/" target="_blank">About Me</a></li>
            <li class="navitem"><a href ="{%url 'logout' %}"> Logout </a></li>
        </ul>
    </nav>
    <main>
        <div class="main-box">
            <p><b>Search for an ingredient or recipe name:</b></p>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.recipe_name }}
                {{ form.chart_type }}
                <button type="submit">Search</button>
                <a href="{% url 'recipes:recipes' %}"><button type="button">Show all</button></a>
            </form>
            {% if form.is_bound %}
                <p><b>You searched for: {{ form.recipe_name.value }}</b></p>
                {% if not recipes.empty %}
                    <ul>
                    {% for index, recipe in recipes.iterrows %}
                        <li>
                            <h2><a href="{% url 'recipes:detail' pk=recipe.id %}">{{ recipe.name }}</a></h2>
                            <img src="/media/{{ recipe.pic }} " class="uniform-image" />
                        </li>
                    {% endfor %}
                    </ul>
                    <h1>Data Analytics</h1>
                    <img src="data:image/png;base64, {{chart|safe}}">
                {% else  %}
                    <h3>No data</h3>
                {% endif  %}
            {% else  %}
                <ul>
                    {% for recipe in recipes %}
                        <li>
                            <h2><a href="{% url 'recipes:detail' pk=recipe.id %}">{{ recipe.name }}</a></h2>
                            <img src="{{ recipe.pic.url }}" class="uniform-image" />
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </main>
    
</body>
</html>